/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotAvailableRouteImport } from './routes/not-available'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPostRouteImport } from './routes/_authenticated/post'
import { Route as AuthenticatedMyAdsRouteImport } from './routes/_authenticated/my-ads'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as StateCityRouteImport } from './routes/$state.$city'
import { Route as AuthenticatedPostIndexRouteImport } from './routes/_authenticated/post.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicRobotsDottxtRouteImport } from './routes/api/public/robots[.]txt'
import { Route as AuthenticatedPromoteIdRouteImport } from './routes/_authenticated/promote.$id'
import { Route as AuthenticatedPostMultiRouteImport } from './routes/_authenticated/post.multi'
import { Route as AuthenticatedPostLocalRouteImport } from './routes/_authenticated/post.local'
import { Route as AuthenticatedCreditsHistoryRouteImport } from './routes/_authenticated/credits.history'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminModerationDashboardRouteImport } from './routes/_authenticated/admin.moderation-dashboard'
import { Route as AuthenticatedAdminFlagsRouteImport } from './routes/_authenticated/admin.flags'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin.ads'
import { Route as StateCityCategoryRouteImport } from './routes/$state.$city.$category'
import { Route as ApiPublicWebhooksNowpaymentsRouteImport } from './routes/api/public/webhooks/nowpayments'
import { Route as ApiAdminAnalyticsExportRouteImport } from './routes/api/admin/analytics.export'
import { Route as AuthenticatedCreditsInvoiceIdRouteImport } from './routes/_authenticated/credits.invoice.$id'
import { Route as AuthenticatedAdsIdEditRouteImport } from './routes/_authenticated/ads.$id.edit'
import { Route as StateCityCategorySlugRouteImport } from './routes/$state.$city.$category.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotAvailableRoute = NotAvailableRouteImport.update({
  id: '/not-available',
  path: '/not-available',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostRoute = AuthenticatedPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAdsRoute = AuthenticatedMyAdsRouteImport.update({
  id: '/my-ads',
  path: '/my-ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StateCityRoute = StateCityRouteImport.update({
  id: '/$state/$city',
  path: '/$state/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostIndexRoute = AuthenticatedPostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPostRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsDottxtRoute = ApiPublicRobotsDottxtRouteImport.update({
  id: '/api/public/robots.txt',
  path: '/api/public/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPromoteIdRoute = AuthenticatedPromoteIdRouteImport.update({
  id: '/promote/$id',
  path: '/promote/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostMultiRoute = AuthenticatedPostMultiRouteImport.update({
  id: '/multi',
  path: '/multi',
  getParentRoute: () => AuthenticatedPostRoute,
} as any)
const AuthenticatedPostLocalRoute = AuthenticatedPostLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => AuthenticatedPostRoute,
} as any)
const AuthenticatedCreditsHistoryRoute =
  AuthenticatedCreditsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedCreditsRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerationDashboardRoute =
  AuthenticatedAdminModerationDashboardRouteImport.update({
    id: '/moderation-dashboard',
    path: '/moderation-dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFlagsRoute = AuthenticatedAdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const StateCityCategoryRoute = StateCityCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => StateCityRoute,
} as any)
const ApiPublicWebhooksNowpaymentsRoute =
  ApiPublicWebhooksNowpaymentsRouteImport.update({
    id: '/api/public/webhooks/nowpayments',
    path: '/api/public/webhooks/nowpayments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAnalyticsExportRoute = ApiAdminAnalyticsExportRouteImport.update({
  id: '/api/admin/analytics/export',
  path: '/api/admin/analytics/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreditsInvoiceIdRoute =
  AuthenticatedCreditsInvoiceIdRouteImport.update({
    id: '/invoice/$id',
    path: '/invoice/$id',
    getParentRoute: () => AuthenticatedCreditsRoute,
  } as any)
const AuthenticatedAdsIdEditRoute = AuthenticatedAdsIdEditRouteImport.update({
  id: '/ads/$id/edit',
  path: '/ads/$id/edit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StateCityCategorySlugRoute = StateCityCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StateCityCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/not-available': typeof NotAvailableRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/$state/$city': typeof StateCityRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/credits': typeof AuthenticatedCreditsRouteWithChildren
  '/my-ads': typeof AuthenticatedMyAdsRoute
  '/post': typeof AuthenticatedPostRouteWithChildren
  '/$state/$city/$category': typeof StateCityCategoryRouteWithChildren
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/admin/moderation-dashboard': typeof AuthenticatedAdminModerationDashboardRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/credits/history': typeof AuthenticatedCreditsHistoryRoute
  '/post/local': typeof AuthenticatedPostLocalRoute
  '/post/multi': typeof AuthenticatedPostMultiRoute
  '/promote/$id': typeof AuthenticatedPromoteIdRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/post/': typeof AuthenticatedPostIndexRoute
  '/$state/$city/$category/$slug': typeof StateCityCategorySlugRoute
  '/ads/$id/edit': typeof AuthenticatedAdsIdEditRoute
  '/credits/invoice/$id': typeof AuthenticatedCreditsInvoiceIdRoute
  '/api/admin/analytics/export': typeof ApiAdminAnalyticsExportRoute
  '/api/public/webhooks/nowpayments': typeof ApiPublicWebhooksNowpaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/not-available': typeof NotAvailableRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/$state/$city': typeof StateCityRouteWithChildren
  '/credits': typeof AuthenticatedCreditsRouteWithChildren
  '/my-ads': typeof AuthenticatedMyAdsRoute
  '/$state/$city/$category': typeof StateCityCategoryRouteWithChildren
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/admin/moderation-dashboard': typeof AuthenticatedAdminModerationDashboardRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/credits/history': typeof AuthenticatedCreditsHistoryRoute
  '/post/local': typeof AuthenticatedPostLocalRoute
  '/post/multi': typeof AuthenticatedPostMultiRoute
  '/promote/$id': typeof AuthenticatedPromoteIdRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/post': typeof AuthenticatedPostIndexRoute
  '/$state/$city/$category/$slug': typeof StateCityCategorySlugRoute
  '/ads/$id/edit': typeof AuthenticatedAdsIdEditRoute
  '/credits/invoice/$id': typeof AuthenticatedCreditsInvoiceIdRoute
  '/api/admin/analytics/export': typeof ApiAdminAnalyticsExportRoute
  '/api/public/webhooks/nowpayments': typeof ApiPublicWebhooksNowpaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/not-available': typeof NotAvailableRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/$state/$city': typeof StateCityRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/credits': typeof AuthenticatedCreditsRouteWithChildren
  '/_authenticated/my-ads': typeof AuthenticatedMyAdsRoute
  '/_authenticated/post': typeof AuthenticatedPostRouteWithChildren
  '/$state/$city/$category': typeof StateCityCategoryRouteWithChildren
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/_authenticated/admin/moderation-dashboard': typeof AuthenticatedAdminModerationDashboardRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/credits/history': typeof AuthenticatedCreditsHistoryRoute
  '/_authenticated/post/local': typeof AuthenticatedPostLocalRoute
  '/_authenticated/post/multi': typeof AuthenticatedPostMultiRoute
  '/_authenticated/promote/$id': typeof AuthenticatedPromoteIdRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/post/': typeof AuthenticatedPostIndexRoute
  '/$state/$city/$category/$slug': typeof StateCityCategorySlugRoute
  '/_authenticated/ads/$id/edit': typeof AuthenticatedAdsIdEditRoute
  '/_authenticated/credits/invoice/$id': typeof AuthenticatedCreditsInvoiceIdRoute
  '/api/admin/analytics/export': typeof ApiAdminAnalyticsExportRoute
  '/api/public/webhooks/nowpayments': typeof ApiPublicWebhooksNowpaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/not-available'
    | '/privacy'
    | '/safety'
    | '/search'
    | '/terms'
    | '/$state/$city'
    | '/admin'
    | '/credits'
    | '/my-ads'
    | '/post'
    | '/$state/$city/$category'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/flags'
    | '/admin/moderation-dashboard'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/credits/history'
    | '/post/local'
    | '/post/multi'
    | '/promote/$id'
    | '/api/public/robots.txt'
    | '/api/public/sitemap.xml'
    | '/admin/'
    | '/post/'
    | '/$state/$city/$category/$slug'
    | '/ads/$id/edit'
    | '/credits/invoice/$id'
    | '/api/admin/analytics/export'
    | '/api/public/webhooks/nowpayments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/not-available'
    | '/privacy'
    | '/safety'
    | '/search'
    | '/terms'
    | '/$state/$city'
    | '/credits'
    | '/my-ads'
    | '/$state/$city/$category'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/flags'
    | '/admin/moderation-dashboard'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/credits/history'
    | '/post/local'
    | '/post/multi'
    | '/promote/$id'
    | '/api/public/robots.txt'
    | '/api/public/sitemap.xml'
    | '/admin'
    | '/post'
    | '/$state/$city/$category/$slug'
    | '/ads/$id/edit'
    | '/credits/invoice/$id'
    | '/api/admin/analytics/export'
    | '/api/public/webhooks/nowpayments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/not-available'
    | '/privacy'
    | '/safety'
    | '/search'
    | '/terms'
    | '/$state/$city'
    | '/_authenticated/admin'
    | '/_authenticated/credits'
    | '/_authenticated/my-ads'
    | '/_authenticated/post'
    | '/$state/$city/$category'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/flags'
    | '/_authenticated/admin/moderation-dashboard'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/credits/history'
    | '/_authenticated/post/local'
    | '/_authenticated/post/multi'
    | '/_authenticated/promote/$id'
    | '/api/public/robots.txt'
    | '/api/public/sitemap.xml'
    | '/_authenticated/admin/'
    | '/_authenticated/post/'
    | '/$state/$city/$category/$slug'
    | '/_authenticated/ads/$id/edit'
    | '/_authenticated/credits/invoice/$id'
    | '/api/admin/analytics/export'
    | '/api/public/webhooks/nowpayments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NotAvailableRoute: typeof NotAvailableRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  StateCityRoute: typeof StateCityRouteWithChildren
  ApiPublicRobotsDottxtRoute: typeof ApiPublicRobotsDottxtRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  ApiAdminAnalyticsExportRoute: typeof ApiAdminAnalyticsExportRoute
  ApiPublicWebhooksNowpaymentsRoute: typeof ApiPublicWebhooksNowpaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-available': {
      id: '/not-available'
      path: '/not-available'
      fullPath: '/not-available'
      preLoaderRoute: typeof NotAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post': {
      id: '/_authenticated/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AuthenticatedPostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-ads': {
      id: '/_authenticated/my-ads'
      path: '/my-ads'
      fullPath: '/my-ads'
      preLoaderRoute: typeof AuthenticatedMyAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$state/$city': {
      id: '/$state/$city'
      path: '/$state/$city'
      fullPath: '/$state/$city'
      preLoaderRoute: typeof StateCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post/': {
      id: '/_authenticated/post/'
      path: '/'
      fullPath: '/post/'
      preLoaderRoute: typeof AuthenticatedPostIndexRouteImport
      parentRoute: typeof AuthenticatedPostRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots.txt': {
      id: '/api/public/robots.txt'
      path: '/api/public/robots.txt'
      fullPath: '/api/public/robots.txt'
      preLoaderRoute: typeof ApiPublicRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/promote/$id': {
      id: '/_authenticated/promote/$id'
      path: '/promote/$id'
      fullPath: '/promote/$id'
      preLoaderRoute: typeof AuthenticatedPromoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post/multi': {
      id: '/_authenticated/post/multi'
      path: '/multi'
      fullPath: '/post/multi'
      preLoaderRoute: typeof AuthenticatedPostMultiRouteImport
      parentRoute: typeof AuthenticatedPostRoute
    }
    '/_authenticated/post/local': {
      id: '/_authenticated/post/local'
      path: '/local'
      fullPath: '/post/local'
      preLoaderRoute: typeof AuthenticatedPostLocalRouteImport
      parentRoute: typeof AuthenticatedPostRoute
    }
    '/_authenticated/credits/history': {
      id: '/_authenticated/credits/history'
      path: '/history'
      fullPath: '/credits/history'
      preLoaderRoute: typeof AuthenticatedCreditsHistoryRouteImport
      parentRoute: typeof AuthenticatedCreditsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation-dashboard': {
      id: '/_authenticated/admin/moderation-dashboard'
      path: '/moderation-dashboard'
      fullPath: '/admin/moderation-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminModerationDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/flags': {
      id: '/_authenticated/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AuthenticatedAdminFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/$state/$city/$category': {
      id: '/$state/$city/$category'
      path: '/$category'
      fullPath: '/$state/$city/$category'
      preLoaderRoute: typeof StateCityCategoryRouteImport
      parentRoute: typeof StateCityRoute
    }
    '/api/public/webhooks/nowpayments': {
      id: '/api/public/webhooks/nowpayments'
      path: '/api/public/webhooks/nowpayments'
      fullPath: '/api/public/webhooks/nowpayments'
      preLoaderRoute: typeof ApiPublicWebhooksNowpaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/analytics/export': {
      id: '/api/admin/analytics/export'
      path: '/api/admin/analytics/export'
      fullPath: '/api/admin/analytics/export'
      preLoaderRoute: typeof ApiAdminAnalyticsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/credits/invoice/$id': {
      id: '/_authenticated/credits/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/credits/invoice/$id'
      preLoaderRoute: typeof AuthenticatedCreditsInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedCreditsRoute
    }
    '/_authenticated/ads/$id/edit': {
      id: '/_authenticated/ads/$id/edit'
      path: '/ads/$id/edit'
      fullPath: '/ads/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$state/$city/$category/$slug': {
      id: '/$state/$city/$category/$slug'
      path: '/$slug'
      fullPath: '/$state/$city/$category/$slug'
      preLoaderRoute: typeof StateCityCategorySlugRouteImport
      parentRoute: typeof StateCityCategoryRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminFlagsRoute: typeof AuthenticatedAdminFlagsRoute
  AuthenticatedAdminModerationDashboardRoute: typeof AuthenticatedAdminModerationDashboardRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminFlagsRoute: AuthenticatedAdminFlagsRoute,
  AuthenticatedAdminModerationDashboardRoute:
    AuthenticatedAdminModerationDashboardRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCreditsRouteChildren {
  AuthenticatedCreditsHistoryRoute: typeof AuthenticatedCreditsHistoryRoute
  AuthenticatedCreditsInvoiceIdRoute: typeof AuthenticatedCreditsInvoiceIdRoute
}

const AuthenticatedCreditsRouteChildren: AuthenticatedCreditsRouteChildren = {
  AuthenticatedCreditsHistoryRoute: AuthenticatedCreditsHistoryRoute,
  AuthenticatedCreditsInvoiceIdRoute: AuthenticatedCreditsInvoiceIdRoute,
}

const AuthenticatedCreditsRouteWithChildren =
  AuthenticatedCreditsRoute._addFileChildren(AuthenticatedCreditsRouteChildren)

interface AuthenticatedPostRouteChildren {
  AuthenticatedPostLocalRoute: typeof AuthenticatedPostLocalRoute
  AuthenticatedPostMultiRoute: typeof AuthenticatedPostMultiRoute
  AuthenticatedPostIndexRoute: typeof AuthenticatedPostIndexRoute
}

const AuthenticatedPostRouteChildren: AuthenticatedPostRouteChildren = {
  AuthenticatedPostLocalRoute: AuthenticatedPostLocalRoute,
  AuthenticatedPostMultiRoute: AuthenticatedPostMultiRoute,
  AuthenticatedPostIndexRoute: AuthenticatedPostIndexRoute,
}

const AuthenticatedPostRouteWithChildren =
  AuthenticatedPostRoute._addFileChildren(AuthenticatedPostRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRouteWithChildren
  AuthenticatedMyAdsRoute: typeof AuthenticatedMyAdsRoute
  AuthenticatedPostRoute: typeof AuthenticatedPostRouteWithChildren
  AuthenticatedPromoteIdRoute: typeof AuthenticatedPromoteIdRoute
  AuthenticatedAdsIdEditRoute: typeof AuthenticatedAdsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRouteWithChildren,
  AuthenticatedMyAdsRoute: AuthenticatedMyAdsRoute,
  AuthenticatedPostRoute: AuthenticatedPostRouteWithChildren,
  AuthenticatedPromoteIdRoute: AuthenticatedPromoteIdRoute,
  AuthenticatedAdsIdEditRoute: AuthenticatedAdsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StateCityCategoryRouteChildren {
  StateCityCategorySlugRoute: typeof StateCityCategorySlugRoute
}

const StateCityCategoryRouteChildren: StateCityCategoryRouteChildren = {
  StateCityCategorySlugRoute: StateCityCategorySlugRoute,
}

const StateCityCategoryRouteWithChildren =
  StateCityCategoryRoute._addFileChildren(StateCityCategoryRouteChildren)

interface StateCityRouteChildren {
  StateCityCategoryRoute: typeof StateCityCategoryRouteWithChildren
}

const StateCityRouteChildren: StateCityRouteChildren = {
  StateCityCategoryRoute: StateCityCategoryRouteWithChildren,
}

const StateCityRouteWithChildren = StateCityRoute._addFileChildren(
  StateCityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NotAvailableRoute: NotAvailableRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  StateCityRoute: StateCityRouteWithChildren,
  ApiPublicRobotsDottxtRoute: ApiPublicRobotsDottxtRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  ApiAdminAnalyticsExportRoute: ApiAdminAnalyticsExportRoute,
  ApiPublicWebhooksNowpaymentsRoute: ApiPublicWebhooksNowpaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
